### ISSUE TITLE
Error messages when starting the debugger

### ISSUE THREAD

**Issue by jtpio** [QuantStack/xeus-python#119]
An alternative to https://github.com/conda-forge/xeus-python-feedstock/pull/27 would be for `xeus-python` to give an error message when:

- `ptvsd` is missing
- `xpython_debug_logs` folder is missing

**Comment by SylvainCorlay** [comment]
+1

Maybe only error on the first debug request?

**Comment by jtpio** [comment]
Yes that would be enough.

**Comment by JohanMabille** [comment]
I will change the behavior regarding `xpython_debug_logs`, it should be created if it does not exist.

**Comment by jtpio** [comment]
No problem, just wanted to open an issue here to have it "logged" somewhere :)

**Comment by JohanMabille** [comment]
This has been improved in last release.

**Comment by jtpio** [comment]
Thanks @JohanMabille !
