### ISSUE TITLE
kernel crashes with ipywidget `interact` in demo nb

### ISSUE THREAD

**Issue by adriendelsalle** [QuantStack/xeus-python#133]
Hi!
Thank you for your work!
Trying the `xeus-python` kernel with `binder` using your project [badge](https://mybinder.org/v2/gh/QuantStack/xeus-python/stable?filepath=notebooks/xeus-python.ipynb), I noticed a cell causing kernel repeated crashes:

```python
from ipywidgets import interact
@interact
def foo(x = ['a', 'b'], n=(1, 10)):
    print(x * n)
```
I'm not able to help so it's just a simple report.

**Comment by martinRenou** [comment]
Thanks a lot for the report! I'll have a look at it :)

**Comment by martinRenou** [comment]
After some investigation, I found that the kernel dies in the `xmock_kernel::parent_header` method call. The `xeus::get_interpreter().parent_header()` seems to return a reference to an `nl::json` object that does not exist, because whenever you try to print this object or operate on it, the kernel silently dies...

@JohanMabille, I tried replacing the `xeus::xkernel_core::parent_header` method by:
```cpp
const nl::json xkernel_core::parent_header(channel c) const noexcept
{
    return get_parent_header(c);
}
```
(I am basically returning a copy of the parent header instead of a reference to it)
And that fixed the issue. Do you have an idea why the current implementation could fail?

**Comment by JohanMabille** [comment]
That is really weird. You don't have any message in the console where the kernel is launched?

**Comment by martinRenou** [comment]
No I've got nothing. It dies silently...

>

**Comment by JohanMabille** [comment]
Does the following work?

```cpp
inline py::object xmock_kernel::parent_header() const
{
    nl::json tmp = xeus::get_interpreter().parent_header();
    return py::dict(py::arg("header")=tmp.get<py::object>());
}
```

**Comment by martinRenou** [comment]
No it does not, that is what I don't understand. It's like the reference returned by `parent_header` is not valid

**Comment by martinRenou** [comment]
> can you activate core dumps and see what you get?

I'll try

**Comment by martinRenou** [comment]
I could display the segfault:
```
Thread 1 "xpython" received signal SIGSEGV, Segmentation fault.
0x00007ffff7794a7e in nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer>::basic_json(nlohmann::basic_json<std::map, std::vector, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long, unsigned long, double, std::allocator, nlohmann::adl_serializer> const&) [clone .lto_priv.307] ()
   from /home/martin/miniconda3/envs/xeus-python/lib/libxeus-python.so.0
```

**Comment by martinRenou** [comment]
So we set the `parent_header` in the xkernel_core as being a reference to the message's `parent_header`. Is the message object still alive when we try to access the parent header? Maybe it's not

**Comment by JohanMabille** [comment]
> So we set the parent_header in the xkernel_core as being a reference to the message's parent_header.

The header is copied in  `xkernel_core::m_parent`, which is an `std::array`. `xkernel_core::parent_header` returns a constant reference on this object while `xkernel_core::get_parent_header` returns a copy. In both cases the original header must be a valid object.

**Comment by SylvainCorlay** [comment]
This should be fixed with the latest release of xeus. Many thanks to @adriendelsalle for the report.

This was a dangling reference bug which has been around for a while but did not impact us before for some reason.
