### ISSUE TITLE
inspect.getsource does not work

### ISSUE THREAD

**Issue by martinRenou** [QuantStack/xeus-python#135]
```python
import inspect

def foo():
    pass

inspect.getsource(foo)
``` 
does not seem to work in the xpython kernel... 

```
Line 6:   inspect.getsource(foo)

File /home/martin/miniconda3/envs/foo/lib/python3.7/inspect.py, in getsource:
Line 973:   lines, lnum = getsourcelines(object)

File /home/martin/miniconda3/envs/foo/lib/python3.7/inspect.py, in getsourcelines:
Line 955:   lines, lnum = findsource(object)

File /home/martin/miniconda3/envs/foo/lib/python3.7/inspect.py, in findsource:
Line 786:   raise OSError('could not get source code')

OSError: could not get source code
```

Resulting in https://github.com/QuantStack/py2vega/ to not work (**EDIT:** at least not in the case Python functions, it would work with string functions)

**Comment by martinRenou** [comment]
It might be unfixable... Because, we execute the compiled AST tree, not the direct source code. It might be the reason why Python cannot retrieve the source code.

**Comment by SylvainCorlay** [comment]
> It might be unfixable...

Although ipykernel does the same, and this works with ipykernel.
