### ISSUE TITLE
Dropping six.

### ISSUE THREAD

**Issue by SylvainCorlay** [QuantStack/xeus-python#78]
It seems that if `py::exec` get fixed (with respect to calling other functions defined in the same call), we should be able to

 - drop the custom six-based `exec` function.
 - drop the workaround due to the extra function in the traceback.

Also, `six` is used for selecting between PY3 and PY2 in `is_complete_request`.

**Comment by martinRenou** [comment]
https://github.com/pybind/pybind11/issues/1654

**Comment by martinRenou** [comment]
The workaround when using `py::exec` would be to add a `__builtins__` key to the `globals` argument containing the content of the `builtins` module if it's not already there. And in the case of `xis_complete`, we should use the same dict for `globals` and `locals`.

**Comment by martinRenou** [comment]
Fixed
