### ISSUE TITLE
What are the advantages of using xeus-python compared to the ipython kernel?

### ISSUE THREAD

**Issue by pmav99** [QuantStack/xeus-python#98]
Just what the title says :)

**Comment by martinRenou** [comment]
You will find the answer in the following medium post: https://blog.jupyter.org/a-new-python-kernel-for-jupyter-fcdf211e30a8. 

TLDR:
> Obviously, xeus-python does not cover 100% of the features of ipykernel. For examples, IPython magics are not supported yet by xeus-python. However:
> - xeus-python is a lot lighter than ipykernel and IPython combined, which makes it a lot easier to implement new features on top of it. Our next goal is to augment the protocol to implement a Python debugger in JupyterLab.
> - xeus-based kernels are more versatile in that one can overload e.g. the concurrency model. This is something that Kitware’s SlicerJupyter project takes advantage of to integrate with the Qt event loop of their Qt-based desktop application.

;)

We started working on the debugger. Allowing debugging in Jupyter Lab. It is at very^10 early stage. But we will get there.

**Comment by pmav99** [comment]
Thank you for the timely response)

I think that copying this to the README would make sense

**Comment by martinRenou** [comment]
I agree. Will do :)
